import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";
import tailwindcssTypography from "@tailwindcss/typography";
import { fontFamily } from "tailwindcss/defaultTheme.js";

const config = {
  darkMode: ["class"],
  content: [
    "src/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "../../packages/ui/src/components/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
        "2xl": "6rem",
      },
    },
    fontSize: {
      xs: "12px",
      sm: "14px",
      base: "16px",
      xl: "20px",
      "2xl": "1.563rem",
      "3xl": "1.953rem",
      "4xl": "2.441rem",
      "5xl": "3.052rem",
    },
    fontWeight: {
      bold: "700",
      semibold: "700",
      medium: "400",
      regular: "400",
      semilight: "350",
      light: "300",
    },
    zIndex: {
      default: "0",
      deep: "-1",
      nav: "10",
      overlay: "20",
      spinner: "30",
    },
    extend: {
      fontFamily: {
        novum: ["var(--font-volvo-novum)", ...fontFamily.sans],
        broad: ["var(--font-volvo-broad)", ...fontFamily.sans],
      },
      colors: {
        v: {
          main: {
            blue400: "#202a44",
            blue300: "#1B365D",
            blue200: "#7089AC",
            blue100: "#CED9E5",
            white: "#ffffff",
            black: "#000000",
            greyDarkest: "#141414",
            grey1: "#e1dfdd",
            grey2: "#a7aba9",
            grey3: "#888b8d",
            grey4: "#53565a",
          },
          accent: {
            flow: "#2d606f",
            flow1: "#396976",
            flow2: "#678c96",
            flow3: "#96b0b6",
            flow4: "#c3d2d6",
            teal: "#1e6659",
            teal1: "#b8ded8",
            teal2: "#8dc9bf",
            teal3: "#66b3a6",
            teal4: "#50a294",
            leaf: "#426932",
            leaf1: "#c8e691",
            leaf2: "#c8e691",
            leaf3: "#8fc54e",
            leaf4: "#78b833",
            sea: "#1b365d",
            sea1: "#06497a",
            sea2: "#476896",
            sea3: "#7b9ab8",
            sea4: "#d8e1eb",
            sand: "#7d5638",
            sand1: "#ac8464",
            sand2: "#c0a790",
            sand3: "#d8bea4",
            sand4: "#eee2d2",
          },
          functional: {
            green100: "var(--brand-functional-green-100)",
            green200: "var(--brand-functional-green-200)",
            green300: "var(--brand-functional-green-300)",
            green400: "var(--brand-functional-green-400)",
            green600: "var(--brand-functional-green-600)",
            green700: "var(--brand-functional-green-700)",
            green900: "var(--brand-functional-green-900)",
            red100: "var(--brand-functional-red-100)",
            red400: "var(--brand-functional-red-400)",
            red600: "var(--brand-functional-red-600)",
            red700: "var(--brand-functional-red-700)",
            red900: "var(--brand-functional-red-900)",
            blue100: "var(--brand-functional-blue-100)",
            blue200: "var(--brand-functional-blue-200)",
            blue300: "var(--brand-functional-blue-300)",
            blue400: "var(--brand-functional-blue-400)",
            blue500: "var(--brand-functional-blue-500)",
            blue600: "var(--brand-functional-blue-600)",
            blue700: "var(--brand-functional-blue-700)",
            blue800: "var(--brand-functional-blue-800)",
            blue900: "var(--brand-functional-blue-900)",
          },
          grayscale: {
            50: "var(--brand-grayscale-50)",
            100: "var(--brand-grayscale-100)",
            200: "var(--brand-grayscale-200)",
            300: "var(--brand-grayscale-300)",
            400: "var(--brand-grayscale-400)",
            500: "var(--brand-grayscale-500)",
            600: "var(--brand-grayscale-600)",
            700: "var(--brand-grayscale-700)",
            800: "var(--brand-grayscale-800)",
            850: "var(--brand-grayscale-850)",
            900: "var(--brand-grayscale-900)",
            950: "var(--brand-grayscale-950)",
            975: "var(--brand-grayscale-975)",
          },
        },
        border: "var(--border)",
        divider: "var(--divider)",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        none: "0",
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "1rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate, tailwindcssTypography],
} satisfies Config;

export default config;
