version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "pnpm"
    target-branch: "main"

  - package-ecosystem: "pnpm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "pnpm"
      - "web"
    target-branch: "main"

  - package-ecosystem: "pnpm"
    directory: "/apps/studio"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "pnpm"
      - "studio"
    target-branch: "main"

  - package-ecosystem: "pnpm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "pnpm"
      - "ui"
    target-branch: "main"